### ISSUE TITLE
some of the emojis am not able to see on Debian GNU/Linux in pidgin.

### ISSUE THREAD

**Issue by shirishag75** [stv0g/unicode-emoji#14]
Hi there, 
Some of the emojis are not viewable/seen on Debian in pidgin. Have no idea whether it's the implementation of Unicode in Debian which is at fault or something else.  You can see which ones are not viewable in the image below. 

Looking forward to know. 

![unicode-emojis](https://cloud.githubusercontent.com/assets/727626/6092603/03e19566-af0c-11e4-9363-76ed387936d6.png)

**Comment by kdex** [comment]
For all I know, the font you've selected does not contain glyphs for every code point reserved for Emoji characters in Unicode. This isn't Debian's fault, it just means that there are no image files that correspond to your desired characters; the images are normally generated from a font file.

For a by complete set of characters, either use the Apple glyphs or see if the font used to generate these glyphs contains the missing gylphs on non-standard codepoints. You might as well check if there's an update available for the font itself, even. If so, feel free to issue a pull request and help completing this. If not, tough luck.

**Comment by shirishag75** [comment]
@kdex I came to know about your these unicode smileys via davidgfnet/whatsapp-purple repo. See :-

https://github.com/davidgfnet/whatsapp-purple/

and specifically 

> How do I get graphical WhatsApp smileys?

> You need to install and enable the Emoji smiley theme. Just copy one of the subdirectories from  following Git repositories to $HOME/.purple/smileys/ and enable the newly installed theme in the Pidgin preferences window:

>    https://github.com/stv0g/unicode-emoji
>   https://github.com/VxJasonxV/emoji-for-pidgin

so as yours was most updated, git pulled yours. 

I don't know about 

So in effect I'm using androidemoji.ttf but this seems to be outdated as shared in this fedora thread, see https://fedoraproject.org/wiki/Google_AndroidEmoji_fonts . Also the source-code of the font file seems to be  the latest in 2013 sometime as can be seen via https://android.googlesource.com/platform/frameworks/base.git/+log/jb-release/data/fonts

Also the new noto fonts could be tried out perhaps by you and take a call as well. 

I also saw https://en.wikipedia.org/wiki/Emoji#Android and made sure that the font package that has been told to be in Linux is not installed so that there are no conflicts. 

    $ aptitude search ttf-ancient-fonts
    p   ttf-ancient-fonts                                               - Unicode Fonts for Ancient Scripts           

looking forward to hearing from you.

**Comment by kdex** [comment]
@shirishag75 

In that case, you should exchange our AndroidEmoji.ttf file with the [newest version](https://github.com/delight-im/Emoji/blob/master/Android/assets/fonts/AndroidEmoji.ttf) and try rebuilding the graphics again. There's a bash build script in this repository. Run it as soon as you've updated AndroidEmoji.ttf with the above and post your results.

**Comment by shirishag75** [comment]
@kdex 

I tried with the newest version and tried rebuilding the graphics again. First I removed the .ttf file so that there is no confusion 

    :~/games/unicode-emoji/android$ rm *.ttf

Then copied the one from over the other repo. to this :-

    ~/games/Emoji/Android/assets/fonts$ cp AndroidEmoji.ttf ~/games/unicode-emoji/android/

Then tried to rebuild it by using the generate.sh shell script :-

    /games/unicode-emoji/android$ ./generate.sh 
    convert: unable to read font `Android-Emoji' @ warning/annotate.c/RenderType/872.
    convert: unable to read font `Android-Emoji' @ warning/annotate.c/RenderType/872.
    convert: unable to read font `Android-Emoji' @ warning/annotate.c/RenderType/872.
    convert: unable to read font `Android-Emoji' @ warning/annotate.c/RenderType/872.

That warning goes on for a while but finally it stops so hopefully the new version is there. 

I copied the resultant AndroidEmoji.ttf to the .purple/smileys/ 

    ~/games/unicode-emoji/android$ cp AndroidEmoji.ttf ~/.purple/smileys/

and ran it in Pidgin without any issues. But as shared in the README.md of the repository you linked, this exercise was totally pointless as shared in the AndroidEmoji.ttf README.md https://github.com/delight-im/Emoji/blob/master/Android/README.md specificlaly this part :-

> Known issues

> Even with this library, your app cannot display emoji that are not in the EmojiSources.txt file. This is normal behaviour for Android versions prior to 4.4 (KitKat), however, because AndroidEmoji.ttf does not contain newer emoji.

One thing I am/was not sure where the java library should go and what should be done with it. https://github.com/delight-im/Emoji/tree/master/Java

Looking forward to learning from you.

**Comment by kdex** [comment]
Just for the record: Pidgin doesn't understand `.ttf`s in the `~/.purple/smileys` directory, it expects directories with images and a plain-text file (`theme`) that links certain glyphs with certain images (just have a look at one of the three directories that this repository comprises). So really, you should have copied your generated images over, not the font.

Other than that, it seems that this font is kind of dead (or at least deprecated), since Android now uses `NotoColorEmoji.ttf` as of Android 4.4. The monochrome `AndroidEmoji.ttf` font only contains an old (incomplete) set of Emoji characters that were used as a fallback (see [this](https://github.com/delight-im/Emoji/blob/master/Android/README.md#known-issues)).

The Java stuff you mentioned is not relevant for this problem, don't worry about that.

If you wanted to generate the newer set of colored Emoji, [this](https://github.com/gjtorikian/NotoColorEmoji-png) would probably be a good place to start. In order to support Pidgin, one would have to edit the generating script to output (I think) 25×25 px, rename the files to <code-point>.png (not necessary, but a lot cleaner) and generate a `theme` file (already done).

**Comment by shirishag75** [comment]
@kdex just found out about https://github.com/treaki/notocolore . Seems it would do the job as well.

**Comment by stv0g** [comment]
Please see #15, #17 and #18 on how to update the emoji sets.
