### ISSUE TITLE
display 

### ISSUE THREAD

**Issue by jemadux** [stv0g/unicode-emoji#16]
some ppl can not see all emoji when  they have 1366x768 display .. can you make them lil bit smaller ?

**Comment by kdex** [comment]
I agree that this is a problem, as over the years, more emoji will be added to the standard and therefore to this project.

Unfortunately, making the images smaller won't solve the problem of displaying big emoticon lists in `Pidgin`. You should rather open an issue over at the `Pidgin` bug tracker and ask if they could implement a **scrollable** emoticon list to solve this once and for all.

If you insist on your temporary workaround of making the emoticons smaller, just change the `imagemagick` variables somethere in the scripts.
